### ISSUE TITLE
--debug is broken in master

### ISSUE THREAD

**Issue by getreu** [cea-hpc/clustershell#243]
```
$clush --debug -w host1.local -b hostname
Warning: Consider increasing max open files hard limit (4096)
Modifying max open files soft limit: 1024 -> 4096
User interaction: True
Create STDIN worker: False
DEBUG:root:clush: STARTING DEBUG
clush: nodeset=bue1.local fanout=64 [timeout conn=10.0 cmd=0.0] command="hostname"
Exception in thread Task-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ClusterShell-1.6-py2.7.egg/ClusterShell/Task.py", line 397, in _thread_start
    self.excepthook(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/ClusterShell-1.6-py2.7.egg/ClusterShell/CLI/Clush.py", line 661, in clush_excepthook
    raise extype(value)
NameError: global name 'cmd_l' is not defined
```

**Comment by thiell** [comment]
Thanks. Fixed in a94924bad7e02b404dbf30a6cfb9ac982e0aba8b.
