### ISSUE TITLE
What exception is raised in case of node groups misconfiguration?

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#263]
Docs say that `NodeSet.fromall()` raises `NodeSetExternalError` in case of node group misconfiguration, but it seems it is NOT true....

```pycon
>>> print NodeSet.fromall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/ClusterShell/NodeSet.py", line 1126, in fromall
    inst.updaten(inst._parser.all_nodes(groupsource))
  File "lib/ClusterShell/NodeSet.py", line 823, in all_nodes
    all = self.group_resolver.all_nodes(namespace)
  File "lib/ClusterShell/NodeUtils.py", line 296, in all_nodes
    source = self._source(namespace)
  File "lib/ClusterShell/NodeUtils.py", line 282, in _source
    raise GroupResolverSourceError(namespace or "<default>")
ClusterShell.NodeUtils.GroupResolverSourceError: <default>
```

**Comment by thiell** [comment]
This is documented here:
http://clustershell.readthedocs.io/en/v1.7.1/guide/nodesets.html#using-node-groups

Patch: https://review.gerrithub.io/280341
