### ISSUE TITLE
clush + pipe: unexpected IOError (broken pipe)

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#303]
With 1.7.1, broken pipe is sometimes not properly handled on KeyboardInterrupt when clush is piped.
May be hard to reproduce.

```
# clush -w sherlock-hsm[01-04] "tail -f /var/log/lhsmtool_cmd.log" | egrep --color -i 'ERROR|WARN'
sherlock-hsm02: WARNING: push_create: now retrying create() for fid 0x20001492f:0xa86c:0x0
sherlock-hsm01: WARNING: push_create: now retrying create() for fid 0x20001492f:0xa825:0x0
sherlock-hsm01: WARNING: push_create: now retrying create() for fid 0x200014fc6:0x2260:0x0
^Cclush: sherlock-hsm01: exited with exit code 255
clush: sherlock-hsm02: exited with exit code 255
clush: sherlock-hsm04: exited with exit code 255
clush: sherlock-hsm03: exited with exit code 255
Keyboard interrupt.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 757, in clush_excepthook
    clush_exit(128 + signal.SIGINT)
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 736, in clush_exit
    stream.flush()
IOError: [Errno 32] Broken pipe

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/clush", line 10, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 1051, in main
    options.remote != 'no')
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 666, in run_command
    task.resume()
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 799, in resume
    self._resume()
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 762, in _resume
    self._run(self.timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 407, in _run
    self._engine.run(timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/Engine.py", line 690, in run
    self.runloop(timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/EPoll.py", line 130, in runloop
    evlist = self.epolling.poll(timeo + 0.001)
KeyboardInterrupt
```

**Comment by thiell** [comment]
See #305 for a possible test strategy (later).
