### ISSUE TITLE
Defaults._load_workerclass() failure

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#304]
Occurred on a new Fedora 23 VM added to Jenkins (with Python 2.7.11).

```
Error Message

dictionary changed size during iteration

Stacktrace

Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/tests/CLIClushTest.py", line 479, in test_033_worker_pdsh_tty
    None, "%s: foo\n" % HOSTNAME, 0)
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/tests/CLIClushTest.py", line 51, in _clush_t
    expected_rc, expected_stderr)
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/tests/TLib.py", line 78, in CLI_main
    main()
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/lib/ClusterShell/CLI/Clush.py", line 857, in main
    task = task_self()
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/lib/ClusterShell/Task.py", line 1357, in task_self
    return Task(thread=threading.currentThread(), defaults=defaults)
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/lib/ClusterShell/Task.py", line 293, in __init__
    "distant_worker": _distant_workerclass(defaults)})
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/lib/ClusterShell/Defaults.py", line 79, in _distant_workerclass
    return _load_workerclass(defaults.distant_workername)
  File "/var/jenkins/workspace/clustershell-gerrithub/label/fedora23/lib/ClusterShell/Defaults.py", line 67, in _load_workerclass
    if modname.lower() not in [mod.lower() for mod in sys.modules]:
RuntimeError: dictionary changed size during iteration
```

**Comment by thiell** [comment]
Ok there are many similar issues on the web, it's clearly a defect. I guess here we should use `sys.modules.keys()` instead of just in `sys.modules` that iterates over the keys of the dictionary, thus has the restriction on modifications (another thread can import new modules at the same time).

**Comment by degremont** [comment]
Seems a good strategy. Looks like an easy fix.
