### ISSUE TITLE
_set_write_eof: self.streams: KeyError: 'stdin'

### ISSUE THREAD

**Issue by martinetd** [cea-hpc/clustershell#320]
We sometimes get that error when ssh (!) fails:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 746, in clush_excepthook
    raise exp                                                                                     
KeyError: 'stdin'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/clush", line 10, in <module>
    main()                                   
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 1051, in main
    options.remote != 'no')                                                            
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 666, in run_command
    task.resume()                                                                            
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 799, in resume
    self._resume()                                                                 
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 762, in _resume
    self._run(self.timeout)                                                         
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 407, in _run
    self._engine.run(timeout)                                                    
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/Engine.py", line 690, in run
    self.runloop(timeout)                                                                
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/EPoll.py", line 165, in runloop
    client._handle_read(sname)                                                              
  File
  "/usr/lib/python2.6/site-packages/ClusterShell/Worker/EngineClient.py", line 510, in _handle_read
    self.eh.ev_msg(self, pmsg.get())                                                               
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 84, in ev_msg
    self.master_worker.set_write_eof()                                                 
  File "/usr/lib/python2.6/site-packages/ClusterShell/Worker/Exec.py", line 365, in set_write_eof
    client._set_write_eof(sname or self.SNAME_STDIN)                                             
  File
  "/usr/lib/python2.6/site-packages/ClusterShell/Worker/EngineClient.py", line 404, in _set_write_eof
    wfile = self.streams[sname]                                                                      
KeyError: 'stdin'
```

A simple workaround would be to just check if the key exists and do nothing if there's no stream to set eof on, but I'd like to debug a bit and understand why there's no streams.

It happens a couple of times a day so we can add logging in ``set_write_eof`` if you know what would be nice to print (currently just checked  ``len(self._clients) == len(self.nodes)`` and printing commands)

Thanks!

**Comment by degremont** [comment]
@martinetd Could you confirm that this implies using some gateways? And could you tell what is ``self.streams.keys()`` content when this occurs?

**Comment by martinetd** [comment]
No gateway involved, this is on an old flat (small 72/32 nodes commands) cluster.

The client failing has stdout/stderr in streams but not stdin (added that back to logging to double-check and will dump keys for other clients too)

**Comment by thiell** [comment]
Thanks for the bug report, this is interesting. I believe it is just a race we don't handle yet... checking quickly, clush's _stdin_thread_start() sends a None message to indicate EOF:
```python
    # send a None message to indicate EOF
    stdin_port.msg(None)
```
So first thing to check is  why this code is triggered while there are still clients running (could be EOF on clush stdin, IOError? but in that case a message should be printed in verbose -v mode).

When received, the None message is checked in StdInputHandler.ev_msg():
```python
        if not msg:
            self.master_worker.set_write_eof()
            return
```

Then, in ExecWorker we call the following method:

```python
    def set_write_eof(self, sname=None):
        """
        Tell worker to close its writer file descriptors once flushed. Do not
        perform writes after this call.
        """
        for client in self._clients:
            client._set_write_eof(sname or self.SNAME_STDIN)
```

So EOF is propagated to all registered EngineClients, however, an EngineClient could possibly have  previous issue on its stdin (like a failed ssh?) and so already closed a stream (like stdin here), and there is no check there for that...

To confirm this theory, we'll have to find a way to reproduce this behavior!

**Comment by martinetd** [comment]
Nice.
Thanks for the theory, I found a reproducer ;)

`echo | clush -w foobar[0-11] -o'-p 4213' echo`
The foobar[0-11] hosts must be alive and respond immediatly (so the ssh fails immediatly); the first `echo|` will close clush's stdin "while" the ssh connections are closing themselves

**Comment by martinetd** [comment]
Odd, can't reproduce on the actual cluster I have the problem with, but it is the correct stack trace on test cluster.... (nodes don't actually need to exist, fun)

```
Warning: fd_max set to 8192 but max open files hard limit is 4096
Changing max open files soft limit from 1024 to 4096
User interaction: False
Create STDIN worker: True
DEBUG:root:clush: STARTING DEBUG
clush: nodeset=foobar[0-11] fanout=64 [timeout conn=15.0 cmd=0.0] command="echo"
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar9 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar6 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar7 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar8 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar0 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar2 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar10 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar3 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar11 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar4 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar1 echo
SSHCLIENT: ssh -a -x -oConnectTimeout=15 -oBatchMode=yes foobar5 echo
WARNING:ClusterShell.Worker.EngineClient:<ClusterShell.Worker.Ssh.SshClient instance at 0x229aa28>: [Errno 32] Broken pipe
WARNING:ClusterShell.Worker.EngineClient:<ClusterShell.Worker.Ssh.SshClient instance at 0x229ab00>: [Errno 32] Broken pipe
WARNING:ClusterShell.Worker.EngineClient:<ClusterShell.Worker.Ssh.SshClient instance at 0x229aa28>: [Errno 32] Broken pipe
foobar9: ssh: Could not resolve hostname foobar9: Name or service not known
foobar9: ssh: Could not resolve hostname foobar9: Name or service not known
foobar6: ssh: Could not resolve hostname foobar6: Name or service not known
foobar6: ssh: Could not resolve hostname foobar6: Name or service not known
clush: foobar9: exited with exit code 255
clush: foobar6: exited with exit code 255
clush: foobar8: exited with exit code 255
clush: foobar0: exited with exit code 255
clush: foobar10: exited with exit code 255
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 751, in clush_excepthook
    raise exp
KeyError: 'stdin'

Original exception was:
Traceback (most recent call last):
  File "./scripts/clush", line 10, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 1069, in main
    options.remote != 'no')
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 667, in run_command
    task.resume()
  File "/usr/lib/python2.7/site-packages/ClusterShell/Task.py", line 799, in resume
    self._resume()
  File "/usr/lib/python2.7/site-packages/ClusterShell/Task.py", line 762, in _resume
    self._run(self.timeout)
  File "/usr/lib/python2.7/site-packages/ClusterShell/Task.py", line 407, in _run
    self._engine.run(timeout)
  File "/usr/lib/python2.7/site-packages/ClusterShell/Engine/Engine.py", line 700, in run
    self.runloop(timeout)
  File "/usr/lib/python2.7/site-packages/ClusterShell/Engine/EPoll.py", line 165, in runloop
    client._handle_read(sname)
  File "/usr/lib/python2.7/site-packages/ClusterShell/Worker/EngineClient.py", line 520, in _handle_read
    self.eh.ev_msg(self, pmsg.get())
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 85, in ev_msg
    self.master_worker.set_write_eof()
  File "/usr/lib/python2.7/site-packages/ClusterShell/Worker/Exec.py", line 365, in set_write_eof
    client._set_write_eof(sname or self.SNAME_STDIN)
  File "/usr/lib/python2.7/site-packages/ClusterShell/Worker/EngineClient.py", line 415, in _set_write_eof
    wfile = self.streams[sname]
KeyError: 'stdin'
```

I guess it's not too bad to do as originally suggested then? Shall I submit something like this (+comment)? Or do you want to handle the Broken pipe better somehow?

```diff
diff --git a/lib/ClusterShell/Worker/EngineClient.py b/lib/ClusterShell/Worker/EngineClient.py
index f1088bf..f576c42 100644
--- a/lib/ClusterShell/Worker/EngineClient.py
+++ b/lib/ClusterShell/Worker/EngineClient.py
@@ -418,6 +418,9 @@ class EngineClient(EngineBaseTimer):
 
     def _set_write_eof(self, sname):
         """Set EOF on specific writable stream."""
+        if not self.streams.has_key(sname):
+            return
+
         wfile = self.streams[sname]
         wfile.eof = True
         if self._engine and wfile.fd and not wfile.wbuf:
```

**Comment by degremont** [comment]
>  ``      if not self.streams.has_key(sname):``

Please note that ``has_key()`` is strongly deprecated. Use ``in`` construct.

**Comment by thiell** [comment]
Great! Yes, I am ok to just ignore unknown streams at EOF, but a debug message using Python logging facility would be nice in that case (should be visible using clush -d).

For clush, this EOF thing is mostly in place to do some kind of "best effort cleaning" remotely - if a remote command is already dead, there is nothing much we can do anyway.
