### ISSUE TITLE
Exception when using -L and -r together

### ISSUE THREAD

**Issue by kurkale6ka** [cea-hpc/clustershell#331]
Hi,

I realise it doesn't make sense to use those 2 options together but it happened anyway and I got this blocking error:

```
$ clush -Lr -gxxx uptime
Exception in thread Task-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 394, in _thread_start
    self.excepthook(*sys.exc_info())
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 751, in clush_except
hook
    raise exp
AttributeError: 'str' object has no attribute 'regroup'


clush: interrupt (^C to abort task)
clush: in progress(0):

clush: interrupt (^C to abort task)
clush: in progress(0):

clush: interrupt (^C to abort task)
clush: in progress(0):
^CKeyboard interrupt.
```

**Comment by thiell** [comment]
Hey @kurkale6ka, thanks for reporting. This bug seems to be present in 1.7.2 but I can't reproduce the issue with the latest version (1.7.3). Could you please confirm? Thanks!

**Comment by kurkale6ka** [comment]
Hmm,

Sorry, I should've upgraded first.
The issue is gone with version 1.7.3
