### ISSUE TITLE
1.8b2: tree mode issue with new EventHandler.ev_close signature

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#363]
Using shine on head node (1.7.82) using topology with gateways in 1.7.3:
```
# shine status 
Traceback (most recent call last):
  File "/usr/sbin/shine", line 34, in <module>
    sys.exit(Controller().run_command())
  File "/usr/lib/python2.6/site-packages/Shine/Controller.py", line 257, in run_command
    rc = command.filter_rc(command.execute())
  File "/usr/lib/python2.6/site-packages/Shine/Commands/Base/FSLiveCommand.py", line 110, in execute
    result = max(result, self.execute_fs(fs, fs_conf, eh, vlevel))
  File "/usr/lib/python2.6/site-packages/Shine/Commands/Status.py", line 86, in execute_fs
    fanout=self.options.fanout)
  File "/usr/lib/python2.6/site-packages/Shine/Lustre/FileSystem.py", line 510, in status
    self._run_actions()
  File "/usr/lib/python2.6/site-packages/Shine/Lustre/FileSystem.py", line 260, in _run_actions
    task_self().resume()
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 803, in resume
    self._resume()
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 766, in _resume
    self._run(self.timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 400, in _run
    self._engine.run(timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/Engine.py", line 723, in run
    self.runloop(timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/EPoll.py", line 170, in runloop
    self.remove_stream(client, stream)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/Engine.py", line 520, in remove_stream
    self.remove(client)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/Engine.py", line 495, in remove
    self._remove(client, abort, did_timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Engine/Engine.py", line 483, in _remove
    client._close(abort=abort, timeout=did_timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Worker/Exec.py", line 141, in _close
    self.worker._check_fini()
  File "/usr/lib/python2.6/site-packages/ClusterShell/Worker/Exec.py", line 382, in _check_fini
    self._has_timeout)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Worker/Worker.py", line 52, in _eh_sigspec_invoke_compat
    return method(*args)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Worker/Tree.py", line 94, in ev_close
    self.metaworker._check_fini()
  File "/usr/lib/python2.6/site-packages/ClusterShell/Worker/Tree.py", line 460, in _check_fini
    handler.ev_close(self, self._has_timeout)
TypeError: ev_close() takes exactly 2 arguments (3 given)
```

**Comment by thiell** [comment]
It's just that the signature check is missing there: it looks like a 1.7-pickled EventHandler object comes from a remote gateway, but the 1.8b2-local WorkerTree calls ev_close() on it with timedout argument without signature check.
Using `_eh_sigspec_invoke_compat()` easily fixes the issue.
Unfortunately this part of the tree code is not tested.

**Comment by thiell** [comment]
clush is working fine, the issue is only present with shine (which is unpickling remote objects).
