### ISSUE TITLE
tests/TaskEventTest: AssertionError: ev_start not called

### ISSUE THREAD

**Issue by arkamar** [cea-hpc/clustershell#488]
I am experiencing weird behavior of tests when I try to run just subset of tests. For example
```sh
nosetests -v --all-modules tests/TaskEventTest.py
```
all tests pass but
```sh
nosetests -v --all-modules tests/StreamWorkerTest.py tests/TaskEventTest.py
```
do not. It fails with `ev_start` related errors (see https://github.com/arkamar/clustershell/runs/8268340929?check_suite_focus=true#step:9:40):
```
======================================================================
FAIL: test ev_pickup event with fanout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/clustershell/clustershell/tests/TaskEventTest.py", line 516, in test_ev_pickup_fanout
    eh.do_asserts_noread_notimeout()
  File "/home/runner/work/clustershell/clustershell/tests/TaskEventTest.py", line 40, in do_asserts_noread_notimeout
    assert self.did_start, "ev_start not called"
AssertionError: ev_start not called

======================================================================
FAIL: test ev_pickup event with fanout (legacy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/clustershell/clustershell/tests/TaskEventTest.py", line 495, in test_ev_pickup_fanout_legacy
    eh.do_asserts_noread_notimeout()
  File "/home/runner/work/clustershell/clustershell/tests/TaskEventTest.py", line 40, in do_asserts_noread_notimeout
    assert self.did_start, "ev_start not called"
AssertionError: ev_start not called
```
Interestingly, if I switch order of files
```sh
nosetests -v --all-modules tests/TaskEventTest.py tests/StreamWorkerTest.py
```
everything works again.

**Comment by thiell** [comment]
Thank you, @arkamar!

**Comment by arkamar** [comment]
@thiell Thanks for the fix and also for https://github.com/cea-hpc/clustershell/commit/aae7bc7ed0e25f612e2adf95d28ae909346a8d53, it is handy for Gentoo package!
